### ISSUE TITLE
License information are missing

### ISSUE THREAD

**Issue by jgjl** [uniker9/JAutoDiff#7]
Hi,

I want to use your library (which is great by the way) in one of my programs.
For that, license information would be helpful. Unfortunately I did not find any
information on this. Neither on the github page, nor in the source code.

**Comment by uniker9** [comment]
Copyright (c) 2012 Yu Nureki uniker9@gmail.com
All rights reserved.
Released under the MIT License.

I will append the license information in the source code soon.

**Comment by jgjl** [comment]
Thank you!
